import { Metadata } from "next";
import { LEGAL_CONFIG } from "@/lib/config/legal";
import Link from "next/link";
import { ArrowLeft, Sparkles } from "lucide-react";

export const metadata: Metadata = {
  title: "AI Output Disclaimer | ALLO",
  description: "Important advisory disclaimer regarding artificial intelligence outputs on ALLO.",
};

export default function AIDisclaimerPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <Link href="/" className="inline-flex items-center text-sm text-indigo-400 hover:text-indigo-300">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to ALLO Home
        </Link>

        <div className="border-b border-slate-800 pb-6">
          <div className="flex items-center gap-3 mb-2">
            <Sparkles className="h-8 w-8 text-indigo-400" />
            <h1 className="text-3xl font-extrabold text-white">AI Output Disclaimer</h1>
          </div>
          <p className="text-sm text-slate-400">
            Last Updated: {LEGAL_CONFIG.lastUpdated}
          </p>
        </div>

        <div className="prose prose-invert max-w-none space-y-6 text-slate-300 text-sm leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">1. Advisory Nature of AI Outputs</h2>
            <p>
              {LEGAL_CONFIG.appName} tools rely on artificial intelligence algorithms ({LEGAL_CONFIG.providers.aiEngine}). While designed to assist productivity, AI-generated content can occasionally contain inaccuracies, incomplete facts, or unexpected formatting. All outputs are advisory and must be independently verified by the user.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">2. Career & Resume Tools</h2>
            <p>
              Resume analysis scores, interview questions, and application suggestions are advisory feedback. ALLO does not guarantee employment, job interviews, or ATS pass rates.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">3. Business & Financial Tools</h2>
            <p>
              Generated invoices, proposals, CRM deals, and startup validation reports do not constitute professional legal, tax, or financial advice. Users remain responsible for reviewing all business documentation before issuing or acting upon them.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">4. Developer & Technical Content</h2>
            <p>
              Code snippets, bug reports, and README files generated by AI should be reviewed and tested prior to deployment in production environments.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
