import { Metadata } from "next";
import { LEGAL_CONFIG } from "@/lib/config/legal";
import Link from "next/link";
import { ArrowLeft, Shield } from "lucide-react";

export const metadata: Metadata = {
  title: "Privacy Policy | ALLO",
  description: "Learn how ALLO collects, uses, processes, and protects your personal and AI tool data.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <Link href="/" className="inline-flex items-center text-sm text-indigo-400 hover:text-indigo-300">
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to ALLO Home
        </Link>

        <div className="border-b border-slate-800 pb-6">
          <div className="flex items-center gap-3 mb-2">
            <Shield className="h-8 w-8 text-indigo-400" />
            <h1 className="text-3xl font-extrabold text-white">Privacy Policy</h1>
          </div>
          <p className="text-sm text-slate-400">
            Last Updated: {LEGAL_CONFIG.lastUpdated} | Version {LEGAL_CONFIG.privacyVersion}
          </p>
        </div>

        <div className="prose prose-invert max-w-none space-y-6 text-slate-300 text-sm leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">1. Overview</h2>
            <p>
              {LEGAL_CONFIG.appName} (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) is an all-in-one AI workspace hosted at {LEGAL_CONFIG.domain}. We respect your privacy and are committed to handling data transparently. This Privacy Policy explains what information we collect, how it is processed, and your choices regarding your data.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">2. Information We Collect</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Account Information:</strong> Name, email address, and authentication credentials managed securely via {LEGAL_CONFIG.providers.authentication}.</li>
              <li><strong>User Content & Inputs:</strong> Data you submit into AI tools (such as resumes, job descriptions, meeting transcripts, startup ideas, and project details).</li>
              <li><strong>AI Generations & Documents:</strong> Outputs generated by AI tools that you save in your workspace history.</li>
              <li><strong>Usage & Operational Data:</strong> AI tool request counts, monthly quota consumption, and timestamps required for usage enforcement.</li>
              <li><strong>Payment Information:</strong> Subscriptions are processed via {LEGAL_CONFIG.providers.paymentGateway}. ALLO does NOT store credit card numbers, CVV, or banking PINs.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">3. Third-Party AI & Infrastructure Providers</h2>
            <p>
              To deliver structured AI tools, requests are processed using third-party infrastructure providers including {LEGAL_CONFIG.providers.aiEngine} and hosted on {LEGAL_CONFIG.providers.database}. Your inputs are sent to the AI API solely to generate your requested outputs and operate the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">4. Data Retention</h2>
            <p>
              Your saved documents, AI generation history, and account settings are retained while your account remains active. Transaction and billing records are retained as required by applicable tax and accounting laws.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">5. Your Privacy Rights & Contact</h2>
            <p>
              You have the right to request access to your stored workspace documents, request export of your data, or request account deletion by navigating to your Privacy Settings or contacting us at:
            </p>
            <p className="font-semibold text-indigo-400">
              Email: {LEGAL_CONFIG.privacyEmail}
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
